name: release-mac

on:
  push:
    tags:
      - '*'

jobs:
  release-mac:
    name: release-mac
    runs-on: macos-11
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@^7

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Packing for mac
        run: |
          rm -rf ./.github
          npm run pack:mac
          npm run pack:mac-arm

      - name: Create zip package
        run: |
          npm run build:mac-zip
          npm run build:mac-arm-zip

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true

